export const properties = [
    {
      id: 1,
      title: "Spacious Family Home",
      location: "Lanark, Scotland",
      price: "£1,250,000",
      status: "For Sale",
      type: "Residential",
      image: "/images/44stleanords.jpg",
      beds: 3,
      baths: 1,
    },
    {
      id: 2,
      title: "Centeral Located Apartment",
      location: "Carluke, Scotland",
      price: "£2,500 pcm",
      status: "For Rent",
      type: "Rental",
      image: "/images/5stewartplace.jpg",
      beds: 2,
      baths: 1,
    },
    {
      id: 3,
      title: "Renovated Mansion",
      location: "In your dreams",
      price: "£5,000,000",
      status: "Investment",
      type: "Flip",
      image: "/images/prop4.jpg",
      beds: 25,
      baths: 32,
    },
  ];