export const properties = [
    {
      id: 1,
      title: "Spacious Family Home",
      location: "Lanark, Scotland",
      price: "£100,000",
      status: "For Sale",
      type: "Residential",
      image: "images/44stleanords.jpg",
      beds: 3,
      baths: 1,
    },
    {
      id: 2,
      title: "Central Located Apartment",
      location: "Carluke, Scotland",
      price: "£1,000 pcm",
      status: "For Rent",
      type: "Rental",
      image: "images/5stewartplace.jpg",
      beds: 2,
      baths: 1,
    },
    {
      id: 3,
      title: "Coming Soon",
      location: "UK",
      price: "£££",
      status: "Coming Soon",
      type: "Flip",
      image: "images/placeholder.png",
      beds: "+",
      baths: "+",
    },
  ];